### ISSUE TITLE
Ajout d'un Namespace dédié aux plugins

### ISSUE THREAD

**Issue by ColonelMoutarde** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#16]
Demander la création d'un namespace dédié aux plugins à l'équipe Jeedom SAS

**Comment by rocket13011** [comment]
un compte market ?

**Comment by ColonelMoutarde** [comment]
Non un namespace au sens php du terme

**Comment by ColonelMoutarde** [comment]
Jeedom/Plugins pour pouvoir faire de l'autoloading facilement via composer
