### ISSUE TITLE
Changer l'id d'un plugin

### ISSUE THREAD

**Issue by ghost** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#17]
Demander à l'équipe Jeedom une méthode pour changer l'id d'un plugin

**Comment by ghost** [comment]
Une fois la solution trouvé, faire une issue pour chaque plugin pour qu'il respectent la norme psr-2

**Comment by cyrilphoenix71** [comment]
Cela peut etre une action volontaire de l'utilisateur sur son Jeedom (action guidée) afin de pouvoir "recuperer" les mise a jour du plugin qui lui aurait deja changé de nom sur le market

**Comment by ghost** [comment]
Je pense qu'il faut trouver une solution automatique car sinon on va perdre les utilisateurs labda.
Mais par exemple edicter des règles d'id de plugin.
Nommage de la forme XxxxYyyy.
Donc le plugin ipx800 par exemple doit devenir Ipx800.
Donc le plugin veolia_eau par exemple doit devenir VeoliaEau.
Donc lors du check de mise à jour, rechercher le plugin avec id historique et id normalisé.
Reste quelques cas à traiter manuellement :
publiemeteo qui devrait devenir PublieMeteo
Pour celà il faudra que le développeur du plugin fasse un message d'information claire lors de la dernière mise à jour de l'ancien plugin mais c'est gérable.
