### ISSUE TITLE
Prise en compte dynamique de l'icone contenu dans le plugin

### ISSUE THREAD

**Issue by ghost** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#18]
Lorsque l'on met à jour un plugin, si l'on change l'icone, il n'est pas pris en compte par le market.

**Comment by rocket13011** [comment]
c'est du cache navigateur. un ctrl + F5 normalement et hop c'est tout bon ;)

**Comment by cyrilphoenix71** [comment]
Je ne pense pas, quand on publie un plugin on nous demande une icône, plutôt que de récupérer dans dossier plugin info. 

Si on choisit rien le plugin de retrouve avec une icône vide

**Comment by ghost** [comment]
Non, je veux dire que lorsque l'on envoie un plugin sur le market, si l'on modifie le fichier plugin_info/XXXX_icon.png, celui-ci n'est pas pris en compte par le market. Il conserve l'ancien icone.

**Comment by rocket13011** [comment]
l'icône changement uniquement si elle viens de la version Stable !
