### ISSUE TITLE
Avoir un référentiel des évolutions Jeedom

### ISSUE THREAD

**Issue by ghost** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#22]
Avoir un référentiel (auquel on puisse s'abonner) des évolutions du core à venir ayant un impact potentiel ou avéré sur les plugins, une sorte de roadmap afin de pouvoir anticiper les mise à jour/adaptations.

**Comment by rocket13011** [comment]
Nous sommes en train de mettre en place un Discourse Dev et une newsletter.
Vous allez tous recevoir un email de Jeedom d'ici a Fin Avril. vous invitent a intégrer notre nouveau service Dev ^^
