### ISSUE TITLE
Publier une interface plugin pour Jeedom

### ISSUE THREAD

**Issue by slobberbone** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#23]
Mettre à disposition une interface que tout plugin doit interfacer. cf : http://php.net/manual/en/language.oop5.interfaces.php

**Comment by ColonelMoutarde** [comment]
Je vote pour ! Mais pour le moment aucune méthode n'est obligatoire. Par compte pour certaines classes on est obligé d'en hériter (cmd et eqlogique).

**Comment by slobberbone** [comment]
Oui mais justement c'est troublant ...

**Comment by ColonelMoutarde** [comment]
Absolument !
