### ISSUE TITLE
Disposer d'un utilisateur Global Jeeom-Plugins-Extra

### ISSUE THREAD

**Issue by slobberbone** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#24]
- Permettre la publication de nouveaux plugins via un compte Jeedom-Plugins-Extra.

- Permettre le changement d'utilisateur des plugins existants vers Jeedom-Plugins-Extra

- Permettre la gestion de dons PayPal par plugin et non par utilisateur

**Comment by rocket13011** [comment]
Permettre la publication de nouveaux plugins via un compte Jeedom-Plugins-Extra. > **OK, attention légalement il faudrait une personne physique ou moral dédié a ce compte.**
Permettre le changement d'utilisateur des plugins existants vers Jeedom-Plugins-Extra > **OK mais il nous faut toute la liste en une fois.**
Permettre la gestion de dons PayPal par plugin et non par utilisateur > **Je ne comprend pas ou ?**

Ou sinon vous avez votre compte chacun, mais on peut mettre un fanions Plugin-Extra. (un peux comme Officiel ou conseillé).

**Comment by slobberbone** [comment]
@rocket13011 

- Pour la personne morale, il te faut quoi comme information ? (Email, association, organisation Github ?)
- Pour la liste des plugins à migrer, serait-il possible d'ouvrir chez nous ou sur le github Jeedom une issue pour ça ? car nous risquons d'avoir des arrivées de plugins lorsqu'on aura communiquer !
- Pour le paiement Paypal, le plus simple serait de pouvoir avoir un lien Paypal sur un plugin et non sur l'utilisateur, avoir un champ supplémentaire lorsqu'on rajoute un plugin pour péciser une url Paypal
- Le fanion Plugins-Extra peut en tout les cas donner de la visibilité !
