### ISSUE TITLE
Gestion des versions 

### ISSUE THREAD

**Issue by ghost** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#26]
Proposer une solution pour connaître la version installée par un client et celle sur gîthub.
En effet la date actuelle correspond généralement à la dernière modification de la documentation.

**Comment by cyrilphoenix71** [comment]
En lien avec l'issue sur le tag des versions ..

**Comment by slobberbone** [comment]
Je pense que c'est à mettre en relation avec https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/issues/25
