### ISSUE TITLE
Donner la possibilité aux utilisateurs d'ouvrir des tickets sur gîthub pour les plugins tiers

### ISSUE THREAD

**Issue by ghost** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#27]

**Comment by cyrilphoenix71** [comment]
Avoir un lien/bouton sur page config du plugin qui ouvre une issue github ?

**Comment by ghost** [comment]
En fait pour moi il faudrait que pour les plugins tiers, la page d'ouverture de ticket "Jeedom" pointe si le plugin a un dépot github sur la page issue de celui-ci.
Je pense au bouton "!" en haut à droite de Jeedom.

**Comment by rjullien** [comment]
> Avoir un lien/bouton sur page config du plugin qui ouvre une issue github ?

Je suis plus pour cette solution, avoir une integration complete Jeedom donne l'impression que le plugin est supporté par Jeedom.

**Comment by ghost** [comment]
Dans ce cas que ce soit clairement affiché genre que le texte de soumission varie :
Envoyer à Jeedom Sas
Envoyer au développeur du plugin.
L'idée étant que l'utilisateur n'ai pas besoin d'aller à un endroit différent pour ouvrir un appel en fonction de qui a développé le plugin.
