### ISSUE TITLE
Wikis

### ISSUE THREAD

**Issue by cyrilphoenix71** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#29]
Reprendre certains de nos wikis dans la doc/site officiel.
Y-a-t-il d'ailleurs quelques part une section wiki/tuto (hors forum) ?

**Comment by ghost** [comment]
Effectivement, il faudrait un truc officiel pour les développeurs avec doc tuto, ...
Du spécial développeur.
A moins que la page de notre team ne soit officiellement décrétée comme page à ce titre ;-)

**Comment by slobberbone** [comment]
Je ne vois aucun inconvénient à ce que Jeedom SAS se serve de notre travail pour aider les devs qu'ils fassent partie de la team ou non ...

**Comment by rjullien** [comment]
Je suis pour un wiki dev, la doc est uniquement dans le forum ca prend un temps infini a lire et ce n'est plus forcement a jour.
> A moins que la page de notre team ne soit officiellement décrétée comme page à ce titre ;-)

ca me parait une bonne idée.

**Comment by rocket13011** [comment]
Nous pensons fork les docs qui nous semble utile pour Jeedom SAS. on trouve votre travail vraiment sympa et cela peux aider les prochains Dev qu'il soit dans votre groupe ou pas ;)
très bon travail !
