### ISSUE TITLE
Icones plugins

### ISSUE THREAD

**Issue by cyrilphoenix71** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#3]
Une des question importante à régler dans le cadre de notre organisation et notre charte graphique concerne les icônes des plugins associés à la Team.

1 - L'icone du plugin sera : 
[![](https://api.gh-polls.com/poll/01C6AABPHSPZSS6TE4MQHA44DT/Ic%C3%B4ne%20de%20l'auteur)](https://api.gh-polls.com/poll/01C6AABPHSPZSS6TE4MQHA44DT/Ic%C3%B4ne%20de%20l'auteur/vote)
[![](https://api.gh-polls.com/poll/01C6AABPHSPZSS6TE4MQHA44DT/Ic%C3%B4ne%20retravaill%C3%A9e%20(couleur%20Team%2C%20ombre...))](https://api.gh-polls.com/poll/01C6AABPHSPZSS6TE4MQHA44DT/Ic%C3%B4ne%20retravaill%C3%A9e%20(couleur%20Team%2C%20ombre...)/vote)
[![](https://api.gh-polls.com/poll/01C6AABPHSPZSS6TE4MQHA44DT/Nouvelle%20ic%C3%B4ne)](https://api.gh-polls.com/poll/01C6AABPHSPZSS6TE4MQHA44DT/Nouvelle%20ic%C3%B4ne/vote)

2 - La couleur des icônes de la team sera : 
[![](https://api.gh-polls.com/poll/01C6A9Y78QCGC6TEDVVDN8H74A/Multicolor%20(m%C3%A9lange%20de%204%20couleurs%20de%20devs))](https://api.gh-polls.com/poll/01C6A9Y78QCGC6TEDVVDN8H74A/Multicolor%20(m%C3%A9lange%20de%204%20couleurs%20de%20devs)/vote)
[![](https://api.gh-polls.com/poll/01C6A9Y78QCGC6TEDVVDN8H74A/Bleu-vert%20(d'Opening))](https://api.gh-polls.com/poll/01C6A9Y78QCGC6TEDVVDN8H74A/Bleu-vert%20(d'Opening)/vote)
[![](https://api.gh-polls.com/poll/01C6A9Y78QCGC6TEDVVDN8H74A/Grise)](https://api.gh-polls.com/poll/01C6A9Y78QCGC6TEDVVDN8H74A/Grise/vote)
[![](https://api.gh-polls.com/poll/01C6A9Y78QCGC6TEDVVDN8H74A/Autre%20(pr%C3%A9cisez%20en%20commentaire))](https://api.gh-polls.com/poll/01C6A9Y78QCGC6TEDVVDN8H74A/Autre%20(pr%C3%A9cisez%20en%20commentaire)/vote)

![16](https://user-images.githubusercontent.com/18350629/36208007-f8200d38-1197-11e8-89fe-b6e72b999266.png)

![jeedom-plugins-extra](https://user-images.githubusercontent.com/18350629/36207921-bb123b3c-1197-11e8-93b3-452a7be15195.png)

![extra](https://user-images.githubusercontent.com/18350629/36207951-c996c2f4-1197-11e8-9388-3e50ec62e364.png)

**Comment by slobberbone** [comment]
Tu devrais rajouter l'icone d'origine au couleur de la team !

**Comment by cyrilphoenix71** [comment]
C'est l'option 2, retrailler c'est juste ajouter une ombre si ya pas etc) je toucherais pas le dessin

**Comment by cyrilphoenix71** [comment]
Cloture des votes, Icone retravaillée et Couleur bleu-vert d'Opening :)
