### ISSUE TITLE
Renommage de l'organisatin de Jeedom-Plugins-Extra en Plugins-Extra-Jeedom

### ISSUE THREAD

**Issue by ghost** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#42]
Suite à une remarque de la société Jeedom-SAS, il souhaite que nous marquons réélement notre détachement de la société.
Ils sont tout a fait conscient que Jeedom ne peut totalement être exclu de notre nom d'organisation.

Après une réunion téléphonique, nous sommes arrivé à la proposition de renommer  l'organisatin de Jeedom-Plugins-Extra en Plugins-Extra-Jeedom.

Afin d'entériner cet proposition nous vous la soumettons au vote (clôture des réponses le 09/05/2018).

[![](https://api.gh-polls.com/poll/01C9V3CYQGQM1HKM98WZTZRKH2/Pour%20le%20renommage)](https://api.gh-polls.com/poll/01C9V3CYQGQM1HKM98WZTZRKH2/Pour%20le%20renommage/vote)
[![](https://api.gh-polls.com/poll/01C9V3CYQGQM1HKM98WZTZRKH2/Contre%20le%20renommage)](https://api.gh-polls.com/poll/01C9V3CYQGQM1HKM98WZTZRKH2/Contre%20le%20renommage/vote)

**Comment by slobberbone** [comment]
Si vous acceptez ce changement, l'ensemble des projets suivra la même logique : 
- Widgets-Extra-Jeedom
- Core-Extra-Jeedom
- Archives-Extra-Jeedom

**Comment by greenskii** [comment]
Je pense que nous devrions nous détacher complètement du nom Jeedom et juste garder un J dans le nom pour marquer le lien avec Jeedom.

Exemples :
-  JPlugins 
- JPluginsExtra
- JSmartHomePluginsExtra

etc..

Ca permettra aussi au cas ou, d'éviter d'utiliser dans notre nom une marque commerciale qui pourrait nous être opposée si les choses ne se passaient pas très bien.

**Comment by slobberbone** [comment]
@greenskii la proposition faite convient à Jeedom SAS. Si un jour nos opinions divergent de trop, nous nous poserons la question d'un fork et dans ce cas nous changerons de nom pour coller au nom du fork.

**Comment by slobberbone** [comment]
Pour ceux qui ne sont contre, je trouverai intéressant de nous dire pourquoi ?
Pour moi qui ne suis pas contre, ce qui va etre pénible c'est de revoir les noms des comptes mails ect utilisé pour les différents services. Clairement c'est pénible. Mais si Jeedom SAS voit notre effort, j ene doute pas qu'ils en feront à leur tour.
Voilà pour moi

**Comment by Sylvaner** [comment]
Nous pourrions lister les conséquences afin de s'y préparer ?
Je vois : 
 - Reconfiguration des dépots locaux (pas très grave),
 - Changement des URL,

**Comment by slobberbone** [comment]
- Changement de l'email de référence
- Changement du nom de l'organisation sur Gitter
- Changement du nom de l'organisation sur Travis
- Changement du nom de l'organisation sur Waffle

**Comment by slobberbone** [comment]
A tous, le vote prendra fin demain soir !

**Comment by slobberbone** [comment]
Chancement effectué : Nouveau nom NextDom après vote.
