### ISSUE TITLE
Respect de la GPL et ambiguïté accès market payant

### ISSUE THREAD

**Issue by slobberbone** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#44]
Problématique concernant l'ambiguïté des accès payant sur le market et partage du code source avec respect de la GPL V2

Document : https://annuel2.framapad.org/p/Plugins-Extra-Jeedom---Open-Source

**Comment by rjullien** [comment]
C'est un problème qui freine l'adoption de jeedom, j'ai pas mal de collègues qui ne veulent pas l'utiliser en disant ce n'est pas vraiment open source. 
Le fait de payer le plugin pourrait être lié au market et au service d'update ultra simple vs copier le source de depuis github.

**Comment by slobberbone** [comment]
Sujet clos faute de communication avec Jeedom SAS
