### ISSUE TITLE
Réflexion autour du plugin-template

### ISSUE THREAD

**Issue by byackee** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#46]
reflexion autour de la structure du plugin-template, doit on se caler sur le plugin de jeedom avec des proposition de modif (PR) ou un plugin indépendant? idées dans la framapad ci-dessous.

https://annuel2.framapad.org/p/plugin-template-jeedom

**Comment by slobberbone** [comment]
Vote pour les propositions à faire : https://framaforms.org/plugin-template-1523456061
A noter que pour les questions concernant ce qui doit être ou non dans le plugin, l'outils : https://github.com/Jeedom-Plugins-Extra/extra-tools permettra d'y ajouter ce qui n'y est pas via un simple menu.
Voilà pourquoi ne pas tout avoir dans le plugin-Template ne posera pas de problème !

**Comment by slobberbone** [comment]
Sujet clos, les discussions avec Jeedom SAS étant rompues.
