### ISSUE TITLE
Pb installation dépendances SNMP avec php7

### ISSUE THREAD

**Issue by fwehrle** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#48]
Hello,

Pas sur d'être au bon endroit pour poster un bug sur le plugin SNMP (le 1er que j'installe depuis NextDom! :)
Mais je remarque qu'il y a 2 sections d'installation des dépendances sur la page de config du plugin : Dépendances et Configuration. Est-ce normal?
Depuis Dépendances, j'ai une erreur dans les logs qui indique ne pas trouver une lib php5. Normal : je suis sous Stretch, donc php7 :)
`########### Installation en cours ##########
Ign:1 http://ftp.fr.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Get:3 http://ftp.fr.debian.org/debian stretch-updates InRelease [91.0 kB]
Hit:4 https://deb.nodesource.com/node_8.x stretch InRelease
Hit:5 http://ftp.fr.debian.org/debian stretch Release
Fetched 91.0 kB in 0s (178 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php5-snmp
sudo: download-mibs: command not found
########### Fin ##########`
Et depuis le paragraphe "Configuration", quand je clique sur "Installer" (les dépendances", j'ai ca : 
`Cannot use SplFileObject with directories`

Voila. Merci à vous

**Comment by slobberbone** [comment]
@fwehrle salut, alors en effet, c'est plutôt ici : https://github.com/NextDom/plugin-SNMP/issues ;)
Le plugin est sur le dépot unstable donc il reste encore des choses à finaliser :) Si tu veux m'aider en le testant, je veux bien :)

**Comment by ColonelMoutarde** [comment]
Salut, je transfert ta demande directement sur le bon plugin. https://github.com/NextDom/plugin-SNMP/issues/18

**Comment by fwehrle** [comment]
Salut @slobberbone et @ColonelMoutarde . Wouah.. z'êtes réactifs! Chapeau! (Et en plus personne pour m'engueuler parce que je poste pas sur le bon fil! ;)
Tiens, j'en profite pour vous dire que je venais de cette page, et que les liens pointent encore sur Jeedom-Extra : https://github.com/NextDom/NextDom/wiki/03-Liste-Plugins-&-Roadmap
Pas de soucis pour tester. J'ai préféré installer un plugin que je n'avais pas encore (SNMP), plutot que ceux que j'utilisent (Teleinfo, IPX800, Ping..), car j'ai peur de perdre mes équipements si j'ajoute un plugin Git alors que je l'ai deja du market : si vous pouviez le préciser sur la doc d'install des plugins market.
Merciii :)
