### ISSUE TITLE
Update / Upgrade Error

### ISSUE THREAD

**Issue by Sigri44** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#58]
Hello,

J'étais en v.0.0.6 full stock sur une VM, j'ai lancé l'update ce matin et voilà le résultat.

Pour le var/html normal c'est un lien symbolic..... Mais pour le reste.. ?

```
>>>>> Directory /var/www/html is empty.. Deleting it ... <<<<<

rmdir: impossible de de supprimer '/var/www/html': N'est pas un dossier
dpkg: erreur de traitement de l'archive /tmp/apt-dpkg-install-tuec49/08-nextdom_0.1.2_all.deb (--unpack) :
 le sous-processus nouveau script pre-installation a retourné une erreur de sortie d'état 1
cp: impossible d'évaluer '/usr/share/nextdom/core/config/common.config.sample.php': Aucun fichier ou dossier de ce type
dpkg: error while cleaning up:
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Préparation du dépaquetage de .../09-nextdom-mysql_0.1.2_all.deb ...
Dépaquetage de nextdom-mysql (0.1.2) sur (0.0.6) ...
Préparation du dépaquetage de .../10-nextdom-common_0.1.2_all.deb ...
Enabling site 000-default.
To activate the new configuration, you need to run:
  systemctl reload apache2
Dépaquetage de nextdom-common (0.1.2) sur (0.0.6) ...
Préparation du dépaquetage de .../11-multiarch-support_2.24-11+deb9u4_amd64.deb ...
Dépaquetage de multiarch-support (2.24-11+deb9u4) sur (2.24-11+deb9u3) ...
Des erreurs ont été rencontrées pendant l'exécution :
 /tmp/apt-dpkg-install-tuec49/08-nextdom_0.1.2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by daodevinc** [comment]
> 
> 
> Hello,
> 
> J'étais en v.0.0.6 full stock sur une VM, j'ai lancé l'update ce matin et voilà le résultat.
> 
> Pour le var/html normal c'est un lien symbolic..... Mais pour le reste.. ?
> 
> ```
> >>>>> Directory /var/www/html is empty.. Deleting it ... <<<<<
> 
> rmdir: impossible de de supprimer '/var/www/html': N'est pas un dossier
> dpkg: erreur de traitement de l'archive /tmp/apt-dpkg-install-tuec49/08-nextdom_0.1.2_all.deb (--unpack) :
>  le sous-processus nouveau script pre-installation a retourné une erreur de sortie d'état 1
> cp: impossible d'évaluer '/usr/share/nextdom/core/config/common.config.sample.php': Aucun fichier ou dossier de ce type
> dpkg: error while cleaning up:
>  le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
> Préparation du dépaquetage de .../09-nextdom-mysql_0.1.2_all.deb ...
> Dépaquetage de nextdom-mysql (0.1.2) sur (0.0.6) ...
> Préparation du dépaquetage de .../10-nextdom-common_0.1.2_all.deb ...
> Enabling site 000-default.
> To activate the new configuration, you need to run:
>   systemctl reload apache2
> Dépaquetage de nextdom-common (0.1.2) sur (0.0.6) ...
> Préparation du dépaquetage de .../11-multiarch-support_2.24-11+deb9u4_amd64.deb ...
> Dépaquetage de multiarch-support (2.24-11+deb9u4) sur (2.24-11+deb9u3) ...
> Des erreurs ont été rencontrées pendant l'exécution :
>  /tmp/apt-dpkg-install-tuec49/08-nextdom_0.1.2_all.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

Resolve en désinstallant réinstallant ! (v0.1.4)
