### ISSUE TITLE
Erreur avec plugin Widget

### ISSUE THREAD

**Issue by titrax35** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra#68]
Avec Nextdom version 0.4.1 et Widget version 2019-05-10 08:06:05.
Impossible de cliquer sur aucun bouton dans la page widget (Market, Ajouter un widget ...)
Rien ne s'ouvre, rien ne se passe. Erreur dans la console firefox :
ReferenceError: Snap is not defined index.php:333:26
ReferenceError: Snap is not defined index.php:344:31
ReferenceError: jwerty is not defined index.php:177:1

Idem avec chrome

**Comment by titrax35** [comment]
Pour corriger le pb en attendant : 
- Télécharger le fichier jwerty.js et le mettre dans plugins/widget/3rdparty (https://github.com/keithamus/jwerty/blob/master/jwerty.js)
- Modifier le fichier nano /usr/share/nextdom/plugins/widget/desktop/php/widget.php
et rajouter 
```
<script src="/plugins/widget/3rdparty/snap.svg-min.js"></script>
<script src="/plugins/widget/3rdparty/jwerty.js"></script>
```
a l extérieur des `<?php ... ?>`(au dessus de `<!--script src="3rdparty/snap.svg/snap.svg-min.js"></script-->`)

**Comment by titrax35** [comment]
doublon avec https://github.com/NextDom/nextdom-core/issues/1367

**Comment by Esso1-jeedom** [comment]
cela fonctionne sur la develop
![image](https://user-images.githubusercontent.com/40739563/65171969-5fbb7080-da4c-11e9-8a8a-493bb411d930.png)
